version: '3.7'

volumes:
  spark-streaming-pg-data:

services:
  postgres:
    image: postgres:10-alpine
    container_name: rockthejvm-sparkstreaming-postgres
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5433:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - spark-streaming-pg-data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:3
    container_name: rockthejvm-sparkstreaming-cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: rockthejvm-sparkstreaming-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: rockthejvm-sparkstreaming-kafka
    ports:
      - "9092:9092"
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_LISTENERS=INTERNAL://kafka:9090,EXTERNAL://:9092"
      - "KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9090,EXTERNAL://localhost:9092"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL"

